/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.clinicav2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author owenv
 */
public class Motivo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Motivo
     */private VHRegistrarCitas c;
     private VHNuevaAdmison a;
     String espe;
     int n;
    public Motivo(VHRegistrarCitas origen) {
        this.c = origen;
        initComponents();
        
                    espe = c.getEspecialidad();
                    cargarTabla(espe);
                    txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
                    public void insertUpdate(DocumentEvent e) {
                        prueba(espe);
                    }

                    public void removeUpdate(DocumentEvent e) {
                        prueba(espe);
                    }

                    public void changedUpdate(DocumentEvent e) {
                        prueba(espe);
                    }
                });
        n = 1;
            
    }
    
    public Motivo(VHNuevaAdmison origen) {
        this.a = origen;
        initComponents();
        
                    espe = a.getEspecialidad();
                    cargarTabla(espe);
                    txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
                    public void insertUpdate(DocumentEvent e) {
                        prueba(espe);
                    }

                    public void removeUpdate(DocumentEvent e) {
                        prueba(espe);
                    }

                    public void changedUpdate(DocumentEvent e) {
                        prueba(espe);
                    }
                });
                    
        n=2;
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void prueba(String especialidad){
            DefaultTableModel m = new DefaultTableModel();
            CConexion co = new CConexion();
            Connection conectado = co.establecerConexion();
            
            String buscar = txtBuscar.getText().trim();
            if(buscar != ""){
                try {
                    String sql = "select id_motivo,motivo from motivos_admision where especialidad = '"+especialidad+"' and motivo like '"+buscar+"%'";
                    PreparedStatement st = conectado.prepareStatement(sql);
                    ResultSet r1 = st.executeQuery();
                    
                    ResultSetMetaData md = r1.getMetaData();
                    int c = md.getColumnCount();
                    
                    String[] cn = new String[c];
                    for(int i = 1; i <= c; i++){
                        cn[i-1] = md.getColumnName(i);
                    }
                    
                    m.setColumnIdentifiers(cn);
                    m.setRowCount(0);
                    
                    while(r1.next()){
                        Object[] f = new Object[c];
                        for(int i = 1; i <= c; i++){
                            f[i-1] = r1.getObject(i);
                        }
                        m.addRow(f);
                    }
                    
                    tablaUbi.setModel(m);
                    
                    r1.close();
                    st.close();
        
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "ERROR: " + ex.getMessage());
                }
            }
}
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUbi = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Motivo");

        tablaUbi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "MOTIVO"
            }
        ));
        jScrollPane1.setViewportView(tablaUbi);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Buscar");

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                int cantidadRep = tablaUbi.getSelectedRow();
                //JOptionPane.showMessageDialog(null, espe);
        
        try{
            CConexion co = new CConexion();
            Connection conectado = co.establecerConexion();
            String ubigeoSelec;
            Statement st = conectado.createStatement();
            String buscar = txtBuscar.getText().trim();
            String sql = "select id_motivo,motivo from motivos_admision where especialidad = '"+espe+"' and motivo like '"+buscar+"%'";

                ResultSet r1 = st.executeQuery(sql);
                int i=0;
                while(i<=cantidadRep){
                    r1.next();
                    i++;
                }
                ubigeoSelec = r1.getString(1);
                     
            
            

            
            if(n==1){
                VHRegistrarCitas.setMotivo(ubigeoSelec);
            }
            if(n==2){
                VHNuevaAdmison.setMotivo(ubigeoSelec);
            }
            
            JOptionPane.showMessageDialog(null, "SELECCIONADO");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "NO SELECCIONADO");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void cargarTabla(String especialidad){
        DefaultTableModel m = new DefaultTableModel();
        m.addColumn("ID");
        m.addColumn("MOTIVO");
        try{
            CConexion co = new CConexion();
            Connection conectado = co.establecerConexion();
            
            Statement st = conectado.createStatement();
            ResultSet r1 = st.executeQuery("select id_motivo,motivo from motivos_admision where especialidad = '"+especialidad+"';");
            
            while(r1.next()){
                Object[] f = new Object[2];
                f[0] = r1.getString(1);
                f[1] = r1.getString(2);
                m.addRow(f);
            }
            
            tablaUbi.setModel(m);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERROR "+ e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUbi;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
