/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.clinicav2;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.*;
import java.awt.event.*;
import java.util.Calendar;
import java.util.HashMap;
public class VHRegistrarCitas extends javax.swing.JInternalFrame {

    
    private static VHRegistrarCitas rpC;
    public VHRegistrarCitas() {
        
        initComponents();
        txtNombre.enable(false);
        txtMotivo1.enable(false);
        btnSelec.setEnabled(false);
        rpC = this;
        txtDoc.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                prueba();
            }

            public void removeUpdate(DocumentEvent e) {
                prueba();
            }

            public void changedUpdate(DocumentEvent e) {
                prueba();
            }
        });
        
        cmbEspecialidad.addItemListener(new java.awt.event.ItemListener() {
            @Override
            public void itemStateChanged(java.awt.event.ItemEvent e) {
                if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                    String seleccion = cmbEspecialidad.getSelectedItem().toString();

                    // Si la especialidad seleccionada no es "Seleccione..." se activa el botón
                    if (!seleccion.equals(" ")) {
                        btnSelec.setEnabled(true);
                    } else {
                        btnSelec.setEnabled(false);
                    }
                }
            }
        });

        
                cmbEspecialidad.addActionListener(new ActionListener() {
            @Override
            
            public void actionPerformed(ActionEvent e) {
                // Obtener el país seleccionado
                
                String medico = (String) cmbEspecialidad.getSelectedItem().toString();
                actualizarmedico(medico);
            }
        });
        
    }
    
    
        private void actualizarmedico(String med){
        String tipoMed = cmbEspecialidad.getSelectedItem().toString();
        cmbMedico.removeAllItems();
        try{
            CConexion co = new CConexion();
            Connection conectado = co.establecerConexion();
            String sql = "select nombre_completo from profesionales p inner join usuarios u ";
            sql = sql + "ON p.id_usuario = u.id_usuario where p.especialidad = '"+tipoMed+"'";
            Statement st1 = conectado.createStatement();
            ResultSet rs1 = st1.executeQuery(sql);
            while(rs1.next()){
                String nomMed =rs1.getString(1);
                cmbMedico.addItem(nomMed);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERROR "+e.getMessage());
        }
    }
    public static void setMotivo(String txt){
            if(rpC !=null){
            javax.swing.SwingUtilities.invokeLater(() ->{
                rpC.txtMotivo1.setText(txt);
            });
        }
    }
    
    public String getEspecialidad() {
        return (String) cmbEspecialidad.getSelectedItem();
    }
    private void prueba(){
        if(txtDoc.getText().length()==8){
            CConexion co = new CConexion();
            Connection conectado = co.establecerConexion();

            String documento = txtDoc.getText().trim();
            try {
                String sql = "select nombre_completo from pacientes p inner join usuarios h ON p.id_paciente = h.id_usuario ";
                sql = sql + "where p.numero_documento = '" + txtDoc.getText() + "'";// + " and h.rol = 'Paciente'" ;

                Statement st1 = conectado.createStatement();
                ResultSet rs1 = st1.executeQuery(sql);

                if (rs1.next()) {
                    String nombreBD = rs1.getString(1);
                    txtNombre.setText(nombreBD);
                }
                rs1.close();
                st1.close();
                conectado.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERROR: " + ex.getMessage());
            }
        }else{
            txtNombre.setText("NO ENCONTRADO");
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jdt = new com.toedter.calendar.JDateChooser();
        txtDoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbEspecialidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbMedico = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtMotivo1 = new javax.swing.JTextField();
        btnSelec = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Programar Citas");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PROGRAMAR CITAS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Fecha de la cita");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Especialidad");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(204, 255, 255), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");

        txtDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Documento");

        cmbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cardiología", "Traumatología", "Pediatría", "Ginecología", "Neurología", "Cirugía General", "Medicina Interna", "Urgencias", "Dermatología", "Oftalmología" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Motivo de admisión");

        cmbMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        cmbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Medico");

        btnSelec.setText("Seleccionar");
        btnSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(cmbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jdt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtMotivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelec))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(121, 122, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMotivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//            Validaciones v = new Validaciones();
//            if(!"".equals(txtDoc.getText()) && !" ".equals(cmbEspecialidad.getSelectedItem().toString()) && !" ".equals(cmbHorario.getSelectedItem().toString()) && !"NO ENCONTRADO".equals(txtNombre.getText()) && !"".equals(txtMotivo.getText())){
//                CConexion co = new CConexion();
//                Connection conectado = co.establecerConexion();
//                try{
//                    String sql = "select p.id_paciente from pacientes p inner join usuarios h ON p.id_paciente = h.id_usuario ";
//                    sql = sql + "where p.numero_documento = '" + txtDoc.getText() + "'";
//                    Statement st1 = conectado.createStatement();
//                    ResultSet rs1 = st1.executeQuery(sql);
//                    rs1.next();
//                    String idpaciente =rs1.getString(1);
//                    
//                    
//
//                    
//                    Statement st2 = conectado.createStatement();
//                    ResultSet rs2 = st2.executeQuery(sql2);
//                    rs2.next();
//                    String idprofesional =rs2.getString(1);
//                    String especialidad = cmbEspecialidad.getSelectedItem().toString();
//                    String motivo = txtMotivo1.getText();
//                            java.util.Date fecha = jdt.getDate();
//                    Calendar c = Calendar.getInstance();
//                    c.setTime(fecha);
//                    int dia = c.get(Calendar.DAY_OF_MONTH);
//                    int mes = c.get(Calendar.MONTH) + 1;
//                    int año = c.get(Calendar.YEAR);
//                    String fechaBD = año + "-" + mes + "-" + dia;
//                    java.sql.Date fechaSQL = java.sql.Date.valueOf(fechaBD);
//                    
//                    String sqlInsertar = "insert into citas (id_paciente,id_profesional,especialidad,motivo,fecha_cita) values(?,?,?,?,?)";
//                    PreparedStatement ps3 = conectado.prepareStatement(sqlInsertar);
//                    ps3.setString(1, idpaciente);
//                    ps3.setString(2, idprofesional);
//                    ps3.setString(3, especialidad);
//                    ps3.setString(4, motivo);
//                    ps3.setDate(5, fechaSQL);
//                    int filaE = ps3.executeUpdate();
//                    JOptionPane.showMessageDialog(null, "CITA AGREGADA");
//                }catch(Exception  e){
//                    JOptionPane.showMessageDialog(null, "error "+e.getMessage());
//                }
//                
//            }else{
//                JOptionPane.showMessageDialog(null, "DATOS INCORRECTOS");
//            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocActionPerformed

    private void cmbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMedicoActionPerformed

    private void btnSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecActionPerformed
        Motivo m = new Motivo(this);
        
        JDesktopPane dp = getDesktopPane();
        if(dp != null){
            dp.add(m);

        }
        m.setLocation(300,350);
        m.setVisible(true);
        
        
    }//GEN-LAST:event_btnSelecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelec;
    private javax.swing.JComboBox<String> cmbEspecialidad;
    private javax.swing.JComboBox<String> cmbMedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser jdt;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtMotivo1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
